#:schema: https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-added-large-files" },
    { id = "check-yaml" },
    { id = "check-toml" },
    { id = "check-merge-conflict" },
]

[[repos]]
repo = "local"
[[repos.hooks]]
id = "ruff-check"
name = "ruff check"
entry = "uvx ruff check ."
language = "system"
types = ["python"]
pass_filenames = false

[[repos.hooks]]
id = "ruff-format"
name = "ruff format"
entry = "uvx ruff format --check ."
language = "system"
types = ["python"]
pass_filenames = false
